plugins {
    id 'com.android.application'
}

android {
    namespace 'com.master.radiomaroc'
    compileSdk 35

    defaultConfig {
        applicationId "com.master.radiomaroc"
        minSdk 24
        targetSdk 35
        versionCode 4
        versionName "4.0"
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
