package com.master.radiomaroc;

import android.Manifest;
import android.app.Activity;
import android.app.AlertDialog;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Typeface;
import android.os.Build;
import android.os.Bundle;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.*;
import java.util.*;

public class MainActivity extends Activity {
    private LinearLayout root;
    private TextView appTitle,appSubtitle,settingsButton,nowPlayingLabel,nowPlaying,status;
    private EditText searchBox;
    private Spinner categorySpinner;
    private Button allButton,favoritesButton,viewButton,toggleButton;
    private Button homeNavButton,favoritesNavButton,settingsNavButton;
    private ImageView playerLogo;
    private GridLayout stationsGrid;
    private SharedPreferences prefs;
    private String lang,viewMode,filterMode="all",categoryFilter="all",currentStationName="",currentState="stopped";
    private Set<String> favorites;
    private boolean currentPlaying=false;

    private static final class StationCardUi {
        final String stationName; final TextView play; final PlayingBarsView bars;
        StationCardUi(String stationName,TextView play,PlayingBarsView bars){this.stationName=stationName;this.play=play;this.bars=bars;}
    }

    private final BroadcastReceiver stateReceiver=new BroadcastReceiver(){@Override public void onReceive(Context context,Intent intent){
        String state=intent.getStringExtra("state"),stationName=intent.getStringExtra("station");
        currentPlaying=intent.getBooleanExtra("playing",false); if(state!=null)currentState=state;
        if(stationName!=null&&!stationName.isEmpty()){currentStationName=stationName;nowPlaying.setText(stationName);Station s=findStation(stationName);if(s!=null)LogoLoader.load(s.logoUrl,s.name,playerLogo,R.drawable.ic_app);}
        if(state!=null)status.setText(stateText(state));toggleButton.setText(currentPlaying?"Ⅱ":"▶");updateStationPlaybackUi();
    }};

    @Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);
        prefs=getSharedPreferences("radio_maroc_prefs",MODE_PRIVATE);lang=prefs.getString("lang","en");viewMode=prefs.getString("view","list");favorites=new HashSet<>(prefs.getStringSet("favorites",new HashSet<>()));
        bindViews();setupCategorySelector();applyLanguage();requestNotificationPermission();buildStationList("");findViewById(R.id.playerBox).setVisibility(View.GONE);
        toggleButton.setOnClickListener(v->toggleRadio());allButton.setOnClickListener(v->setFilter("all"));favoritesButton.setOnClickListener(v->setFilter("favorites"));viewButton.setOnClickListener(v->cycleViewMode());
        settingsButton.setOnClickListener(v->showSettings());homeNavButton.setOnClickListener(v->setFilter("all"));favoritesNavButton.setOnClickListener(v->setFilter("favorites"));settingsNavButton.setOnClickListener(v->showSettings());
        searchBox.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){buildStationList(s==null?"":s.toString());}public void afterTextChanged(Editable s){}});updateModeButtons();updateViewIcon();
    }

    private void bindViews(){root=findViewById(R.id.root);appTitle=findViewById(R.id.appTitle);appSubtitle=findViewById(R.id.appSubtitle);settingsButton=findViewById(R.id.settingsButton);searchBox=findViewById(R.id.searchBox);categorySpinner=findViewById(R.id.categorySpinner);allButton=findViewById(R.id.allButton);favoritesButton=findViewById(R.id.favoritesButton);viewButton=findViewById(R.id.viewButton);playerLogo=findViewById(R.id.playerLogo);nowPlayingLabel=findViewById(R.id.nowPlayingLabel);nowPlaying=findViewById(R.id.nowPlaying);status=findViewById(R.id.status);toggleButton=findViewById(R.id.toggleButton);stationsGrid=findViewById(R.id.stationsGrid);homeNavButton=findViewById(R.id.homeNavButton);favoritesNavButton=findViewById(R.id.favoritesNavButton);settingsNavButton=findViewById(R.id.settingsNavButton);}

    private void applyLanguage(){boolean rtl="ar".equals(lang);root.setLayoutDirection(rtl?View.LAYOUT_DIRECTION_RTL:View.LAYOUT_DIRECTION_LTR);appTitle.setText("Radio Maroc");appSubtitle.setText(t("صوت المغرب أينما كنت","La voix du Maroc, partout avec vous","Moroccan voices, everywhere with you"));searchBox.setHint(t("ابحث عن محطة…","Rechercher une station…","Search stations…"));allButton.setText(t("الكل","Toutes","All"));favoritesButton.setText(t("المفضلة","Favoris","Favorites"));nowPlayingLabel.setText(t("الآن على الهواء","EN DIRECT","NOW PLAYING"));if(currentStationName.isEmpty())nowPlaying.setText(t("اختر محطة","Choisissez une station","Choose a station"));status.setText(stateText(currentStationName.isEmpty()?"stopped":(currentPlaying?"playing":"paused")));settingsButton.setContentDescription(t("الإعدادات","Paramètres","Settings"));homeNavButton.setText(t("⌂\nالرئيسية","⌂\nAccueil","⌂\nHome"));favoritesNavButton.setText(t("★\nالمفضلة","★\nFavoris","★\nFavorites"));settingsNavButton.setText(t("⚙\nالإعدادات","⚙\nParamètres","⚙\nSettings"));}
    private String t(String ar,String fr,String en){return "fr".equals(lang)?fr:("ar".equals(lang)?ar:en);}
    private String categoryTitle(String c){if("islamic".equals(c))return t("إسلامية وقرآن","Islam et Coran","Islamic & Quran");if("public".equals(c))return t("إذاعات عمومية","Radios publiques","Public radio");if("regional".equals(c))return t("إذاعات جهوية","Radios régionales","Regional radio");if("news".equals(c))return t("أخبار","Actualités","News");if("sports".equals(c))return t("رياضة","Sport","Sports");if("amazigh".equals(c))return t("أمازيغية","Amazigh","Amazigh");if("music".equals(c))return t("موسيقى","Musique","Music");if("foreign".equals(c))return t("أجنبية وعالمية","Internationales","Foreign & world");return t("متنوعة وثقافة","Variées et culture","Variety & culture");}

    private void setupCategorySelector(){final String[] keys={"all","islamic","public","regional","news","sports","general","amazigh","music","foreign"};String[] labels={t("التصنيف: كل الأقسام ▼","Catégorie : Toutes ▼","Category: All ▼"),categoryTitle("islamic"),categoryTitle("public"),categoryTitle("regional"),categoryTitle("news"),categoryTitle("sports"),categoryTitle("general"),categoryTitle("amazigh"),categoryTitle("music"),categoryTitle("foreign")};
        ArrayAdapter<String> a=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,labels){@Override public View getView(int p,View v,ViewGroup parent){TextView x=(TextView)super.getView(p,v,parent);x.setTextColor(getColor(R.color.text));x.setTextSize(16);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.setPadding(dp(18),0,dp(18),0);return x;}@Override public View getDropDownView(int p,View v,ViewGroup parent){TextView x=(TextView)super.getDropDownView(p,v,parent);x.setTextColor(getColor(R.color.text));x.setTextSize(16);x.setPadding(dp(20),dp(16),dp(20),dp(16));x.setBackgroundColor(0xFF102735);return x;}};categorySpinner.setAdapter(a);categorySpinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onItemSelected(AdapterView<?> p,View v,int pos,long id){String n=keys[pos];if(!n.equals(categoryFilter)){categoryFilter=n;buildStationList(searchBox.getText().toString());}}public void onNothingSelected(AdapterView<?> p){}});}
    private String stateText(String s){if("connecting".equals(s)||"reconnecting".equals(s))return t("جاري الاتصال…","Connexion…","Connecting…");if("playing".equals(s))return t("● يعمل الآن","● Lecture","● Playing");if("paused".equals(s))return t("متوقف مؤقتًا","En pause","Paused");if("error".equals(s))return t("تعذر تشغيل المحطة","Lecture impossible","Playback unavailable");return t("متوقف","Arrêté","Stopped");}
    private void setFilter(String m){filterMode=m;updateModeButtons();buildStationList(searchBox.getText().toString());}

    private void buildStationList(String query){stationsGrid.removeAllViews();boolean grid="grid".equals(viewMode),compact="compact".equals(viewMode);stationsGrid.setColumnCount(grid?2:1);String q=query==null?"":query.trim().toLowerCase(Locale.ROOT);
        for(Station station:Stations.ALL){if("favorites".equals(filterMode)&&!favorites.contains(station.name))continue;if(!"all".equals(categoryFilter)&&!categoryFilter.equals(station.category))continue;String searchable=(station.name+" "+station.subtitleAr+" "+station.subtitleFr+" "+station.subtitleEn).toLowerCase(Locale.ROOT);if(!q.isEmpty()&&!searchable.contains(q))continue;
            final boolean available=station.hasStream();LinearLayout card=new LinearLayout(this);card.setOrientation(grid?LinearLayout.VERTICAL:LinearLayout.HORIZONTAL);card.setGravity(Gravity.CENTER_VERTICAL);card.setPadding(dp(compact?8:11),dp(compact?7:10),dp(compact?8:11),dp(compact?7:10));card.setBackgroundResource(R.drawable.card_bg);card.setAlpha(available?1f:.62f);GridLayout.LayoutParams cp=new GridLayout.LayoutParams();cp.setMargins(dp(4),dp(4),dp(4),dp(4));cp.height=ViewGroup.LayoutParams.WRAP_CONTENT;if(grid){cp.width=0;cp.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);}else{cp.width=ViewGroup.LayoutParams.MATCH_PARENT;cp.columnSpec=GridLayout.spec(0,1f);}card.setLayoutParams(cp);
            ImageView logo=new ImageView(this);int logoSize=dp(grid?96:(compact?42:58));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(logoSize,logoSize);if(grid){lp.gravity=Gravity.CENTER_HORIZONTAL;lp.bottomMargin=dp(8);}else lp.setMarginEnd(dp(11));logo.setLayoutParams(lp);logo.setScaleType(ImageView.ScaleType.CENTER_INSIDE);logo.setPadding(dp(3),dp(3),dp(3),dp(3));logo.setBackgroundResource(R.drawable.logo_bg);LogoLoader.load(station.logoUrl,station.name,logo,R.drawable.ic_app);
            LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);info.setGravity(grid?Gravity.CENTER_HORIZONTAL:Gravity.CENTER_VERTICAL);info.setLayoutParams(new LinearLayout.LayoutParams(grid?ViewGroup.LayoutParams.MATCH_PARENT:0,ViewGroup.LayoutParams.WRAP_CONTENT,grid?0:1f));TextView name=new TextView(this);name.setText(station.name);name.setTypeface(Typeface.DEFAULT,Typeface.BOLD);name.setTextSize(compact?14:(grid?16:17));name.setTextColor(getColor(R.color.text));name.setGravity(grid?Gravity.CENTER:Gravity.START);name.setMaxLines(grid?2:1);TextView sub=new TextView(this);sub.setText(categoryTitle(station.category)+"  •  "+station.subtitle(lang));sub.setTextColor(getColor(R.color.muted));sub.setTextSize(compact?10:12);sub.setGravity(grid?Gravity.CENTER:Gravity.START);sub.setMaxLines(2);if(!available)sub.setText(sub.getText()+"  •  "+t("غير متاحة مؤقتًا","Indisponible temporairement","Temporarily unavailable"));info.addView(name);info.addView(sub);
            LinearLayout actions=new LinearLayout(this);actions.setGravity(Gravity.CENTER);TextView star=actionText(favorites.contains(station.name)?"★":"☆",R.color.gold);star.setContentDescription(t("المفضلة","Favori","Favorite"));star.setOnClickListener(v->toggleFavorite(station.name,star));boolean selected=station.name.equals(currentStationName);TextView play=actionText(available?(selected&&currentPlaying?"Ⅱ":"▶"):"—",R.color.gold_light);play.setContentDescription(selected&&currentPlaying?t("إيقاف مؤقت","Pause","Pause"):t("تشغيل","Lecture","Play"));play.setAlpha(available?1f:.35f);if(available)play.setOnClickListener(v->{if(station.name.equals(currentStationName))toggleRadio();else playStation(station);});PlayingBarsView bars=new PlayingBarsView(this);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(dp(30),dp(30));bp.setMarginStart(dp(2));bp.setMarginEnd(dp(2));bars.setLayoutParams(bp);bars.setPlaying(selected&&currentPlaying);actions.addView(bars);actions.addView(star);actions.addView(play);card.addView(logo);card.addView(info);card.addView(actions);card.setTag(new StationCardUi(station.name,play,bars));if(available){card.setClickable(true);card.setFocusable(true);card.setOnClickListener(v->{if(station.name.equals(currentStationName))toggleRadio();else playStation(station);});}stationsGrid.addView(card);
        }}
    private TextView actionText(String text,int color){TextView v=new TextView(this);v.setText(text);v.setTextSize(31);v.setTextColor(getColor(color));v.setGravity(Gravity.CENTER);v.setMinWidth(dp(64));v.setMinHeight(dp(64));v.setPadding(dp(12),0,dp(12),0);return v;}
    private void updateStationPlaybackUi(){for(int i=0;i<stationsGrid.getChildCount();i++){View card=stationsGrid.getChildAt(i);Object tag=card.getTag();if(!(tag instanceof StationCardUi))continue;StationCardUi ui=(StationCardUi)tag;boolean selected=ui.stationName.equals(currentStationName);ui.play.setText(selected&&currentPlaying?"Ⅱ":"▶");ui.play.setContentDescription(selected&&currentPlaying?t("إيقاف مؤقت","Pause","Pause"):t("تشغيل","Lecture","Play"));ui.bars.setPlaying(selected&&currentPlaying);}}
    private void toggleFavorite(String n,TextView star){if(favorites.contains(n))favorites.remove(n);else favorites.add(n);prefs.edit().putStringSet("favorites",new HashSet<>(favorites)).apply();star.setText(favorites.contains(n)?"★":"☆");if("favorites".equals(filterMode))buildStationList(searchBox.getText().toString());}
    private void cycleViewMode(){viewMode="list".equals(viewMode)?"compact":("compact".equals(viewMode)?"grid":"list");prefs.edit().putString("view",viewMode).apply();updateViewIcon();buildStationList(searchBox.getText().toString());}
    private void updateViewIcon(){viewButton.setText("grid".equals(viewMode)?"▦":("compact".equals(viewMode)?"☷":"☰"));}
    private void updateModeButtons(){allButton.setAlpha("all".equals(filterMode)?1f:.55f);favoritesButton.setAlpha("favorites".equals(filterMode)?1f:.55f);}

    private void showSettings(){String[] items={"🚘  "+t("وضعية السياقة","Mode conduite","Driving mode"),"🌐  "+t("اللغة","Langue","Language"),"▦  "+t("طريقة العرض","Mode d’affichage","Display mode"),"◷  "+t("مؤقت النوم","Minuterie","Sleep timer"),"ⓘ  "+t("حول البرنامج","À propos","About"),"🔒  "+t("الخصوصية والأمان","Confidentialité et sécurité","Privacy & security")};new AlertDialog.Builder(this).setTitle("⚙  "+t("الإعدادات","Paramètres","Settings")).setItems(items,(d,w)->{if(w==0)startActivity(new Intent(this,DriverActivity.class));else if(w==1)showLanguageDialog();else if(w==2)showViewDialog();else if(w==3)showSleepDialog();else if(w==4)showAboutDialog();else showPrivacyDialog();}).setNegativeButton(t("إغلاق","Fermer","Close"),null).show();}
    private void showLanguageDialog(){String[] o={"English","Français","العربية"};int c="en".equals(lang)?0:("fr".equals(lang)?1:2);new AlertDialog.Builder(this).setTitle("🌐  "+t("اللغة","Langue","Language")).setSingleChoiceItems(o,c,(d,w)->{lang=w==0?"en":(w==1?"fr":"ar");prefs.edit().putString("lang",lang).apply();d.dismiss();recreate();}).show();}
    private void showViewDialog(){String[] o={t("قائمة","Liste","List"),t("قائمة مدمجة","Liste compacte","Compact"),t("صور مصغرة","Vignettes","Thumbnails")};int c="list".equals(viewMode)?0:("compact".equals(viewMode)?1:2);new AlertDialog.Builder(this).setTitle(t("طريقة العرض","Mode d’affichage","Display mode")).setSingleChoiceItems(o,c,(d,w)->{viewMode=w==0?"list":(w==1?"compact":"grid");prefs.edit().putString("view",viewMode).apply();d.dismiss();updateViewIcon();buildStationList(searchBox.getText().toString());}).show();}
    private void showSleepDialog(){String[] o={t("إيقاف","Désactivé","Off"),"15 min","30 min","60 min"};new AlertDialog.Builder(this).setTitle(t("مؤقت النوم","Minuterie","Sleep timer")).setItems(o,(d,w)->{int m=w==1?15:(w==2?30:(w==3?60:0));Intent i=new Intent(this,RadioService.class).setAction(RadioService.ACTION_SLEEP);i.putExtra(RadioService.EXTRA_MINUTES,m);startService(i);}).show();}
    private void showAboutDialog(){String msg=t(
        "راديو المغرب تطبيق مجاني ومفتوح المصدر وبدون إشهارات، أنشئ بهدف الخدمة فقط. المبرمج M@ster لا يطلب من المستخدمين أي أموال أو تبرعات أو تحويلات مالية بأي شكل. أي شخص يطلب المال باسم التطبيق أو المبرمج لا يمثل راديو المغرب. التطبيق يهدف إلى توفير وسيلة بسيطة وآمنة للاستماع إلى الإذاعات المغربية، خصوصاً للجالية المغربية بالخارج.\n\nتنبيه: الإذاعات المتاحة في تطبيق «راديو المغرب» تمثل الجهات المالكة لها ومحتواها الخاص، ولا تعبر عن آراء أو مواقف المبرمج M@ster. إدراج المحطات هدفه إتاحة خيارات متنوعة للمستخدمين، ليختار كل مستخدم المحتوى والإذاعة التي تناسبه.",
        "Radio Maroc est une application gratuite, open source et sans publicité, créée uniquement dans un but de service. Le développeur M@ster ne demande jamais d’argent, de dons ni de virements aux utilisateurs.\n\nAvertissement : les stations disponibles dans Radio Maroc représentent leurs propriétaires et leurs propres contenus. Elles ne reflètent ni les opinions ni les positions du développeur M@ster. Leur présence vise uniquement à offrir un choix large et diversifié afin que chaque utilisateur puisse sélectionner les stations et contenus qui lui conviennent.",
        "Radio Maroc is free, open-source and ad-free, created solely as a public-service project. Developer M@ster never asks users for money, donations or financial transfers.\n\nNotice: The stations available in Radio Maroc represent their respective owners and their own content. They do not reflect the views or positions of developer M@ster. Stations are included solely to provide users with a broad and diverse choice so each user can select the stations and content that suit them.");new AlertDialog.Builder(this).setTitle("Radio Maroc • M@ster").setMessage(msg+"\n\nGPL-3.0-or-later • No ads • No tracking").setPositiveButton("OK",null).show();}
    private void showPrivacyDialog(){String msg=t("لا إعلانات، لا تحليلات، لا تتبع، ولا جمع للبيانات الشخصية. الكود مفتوح المصدر ويمكن تدقيقه.","Aucune publicité, analytique, traçage ni collecte de données personnelles. Le code est open source et vérifiable.","No ads, analytics, tracking, or personal-data collection. The source code is open for audit.");new AlertDialog.Builder(this).setTitle("🔒  "+t("الخصوصية والأمان","Confidentialité et sécurité","Privacy & security")).setMessage(msg).setPositiveButton("OK",null).show();}

    private void playStation(Station s){if(!s.hasStream()){Toast.makeText(this,t("هذه المحطة غير متاحة مؤقتًا","Cette station est temporairement indisponible","This station is temporarily unavailable"),Toast.LENGTH_LONG).show();return;}currentStationName=s.name;nowPlaying.setText(s.name);status.setText(stateText("connecting"));LogoLoader.load(s.logoUrl,s.name,playerLogo,R.drawable.ic_app);Intent i=new Intent(this,RadioService.class).setAction(RadioService.ACTION_PLAY);i.putExtra(RadioService.EXTRA_NAME,s.name);i.putExtra(RadioService.EXTRA_URL,s.streamUrl);if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.O)startForegroundService(i);else startService(i);}
    private void toggleRadio(){startService(new Intent(this,RadioService.class).setAction(RadioService.ACTION_TOGGLE));}
    private Station findStation(String n){for(Station s:Stations.ALL)if(s.name.equals(n))return s;return null;}
    private void requestNotificationPermission(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},100);}
    private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
    @Override protected void onStart(){super.onStart();IntentFilter f=new IntentFilter("com.master.radiomaroc.STATE");if(Build.VERSION.SDK_INT>=33)registerReceiver(stateReceiver,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(stateReceiver,f);startService(new Intent(this,RadioService.class).setAction(RadioService.ACTION_QUERY));}
    @Override protected void onStop(){try{unregisterReceiver(stateReceiver);}catch(Exception ignored){}super.onStop();}
}
