package com.master.radiomaroc;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.media.MediaMetadata;
import android.media.session.MediaSession;
import android.media.session.PlaybackState;
import android.os.*;
import java.io.InputStream;
import java.net.URL;
import java.util.*;
import androidx.media3.common.AudioAttributes;
import androidx.media3.common.C;
import androidx.media3.common.MediaItem;
import androidx.media3.common.PlaybackException;
import androidx.media3.common.Player;
import androidx.media3.datasource.DefaultHttpDataSource;
import androidx.media3.exoplayer.ExoPlayer;
import androidx.media3.exoplayer.source.DefaultMediaSourceFactory;

public class RadioService extends Service {
 public static final String ACTION_PLAY="com.master.radiomaroc.PLAY",ACTION_TOGGLE="com.master.radiomaroc.TOGGLE",ACTION_STOP="com.master.radiomaroc.STOP",ACTION_QUERY="com.master.radiomaroc.QUERY",ACTION_SLEEP="com.master.radiomaroc.SLEEP",ACTION_NEXT="com.master.radiomaroc.NEXT",ACTION_PREVIOUS="com.master.radiomaroc.PREVIOUS";
 public static final String EXTRA_NAME="station_name",EXTRA_URL="station_url",EXTRA_MINUTES="minutes";
 private static final String CHANNEL_ID="radio_playback"; private static final int NOTIFICATION_ID=1001;
 private static final String PREFS="radio_maroc_prefs", ORDER="station_order", SEP="\u001F";
 private ExoPlayer player; private MediaSession mediaSession; private final Handler handler=new Handler(Looper.getMainLooper()); private Runnable sleepRunnable,retryRunnable;
 private String currentName="",currentUrl="",state="stopped"; private boolean prepared=false,playing=false; private Bitmap stationArt; private List<String> sources=Collections.emptyList(); private int sourceIndex=0,retryRound=0,generation=0;

 @Override public void onCreate(){super.onCreate();createChannel();createMediaSession();}
 @Override public int onStartCommand(Intent i,int f,int id){if(i==null)return currentName.isEmpty()?START_NOT_STICKY:START_STICKY;String a=i.getAction();if(ACTION_PLAY.equals(a)){String n=i.getStringExtra(EXTRA_NAME),u=i.getStringExtra(EXTRA_URL);if(n!=null)playStation(n,u);}else if(ACTION_TOGGLE.equals(a))togglePlayback();else if(ACTION_STOP.equals(a))stopPlayback(true);else if(ACTION_NEXT.equals(a))changeStation(1);else if(ACTION_PREVIOUS.equals(a))changeStation(-1);else if(ACTION_QUERY.equals(a)){broadcastState();if(currentName.isEmpty())stopSelf(id);}else if(ACTION_SLEEP.equals(a))scheduleSleep(i.getIntExtra(EXTRA_MINUTES,0));return currentName.isEmpty()?START_NOT_STICKY:START_STICKY;}

 private void playStation(String name,String supplied){generation++;cancelRetry();currentName=name;stationArt=null;loadStationArt(name);Station s=Stations.find(name);ArrayList<String> list=new ArrayList<>();if(s!=null)list.addAll(s.streamUrls);if(supplied!=null&&!supplied.trim().isEmpty()&&!list.contains(supplied))list.add(0,supplied);sources=list;sourceIndex=0;retryRound=0;if(sources.isEmpty()){state="error";broadcastState();return;}startSource(generation);}
 private ExoPlayer buildPlayer(){DefaultHttpDataSource.Factory http=new DefaultHttpDataSource.Factory().setUserAgent("Mozilla/5.0 (Linux; Android 16) AppleWebKit/537.36 Chrome/140 Mobile Safari/537.36 RadioMaroc/5.7").setAllowCrossProtocolRedirects(true).setConnectTimeoutMs(12000).setReadTimeoutMs(20000);Map<String,String> headers=new HashMap<>();headers.put("Accept","*/*");headers.put("Accept-Language","ar,fr;q=0.9,en;q=0.8");if(currentUrl.contains("globecast.akamaized.net")||currentName.startsWith("Radio ")||currentName.contains("محمد السادس")||"Chaîne Inter".equals(currentName)){headers.put("Referer","https://snrtlive.ma/");headers.put("Origin","https://snrtlive.ma");}http.setDefaultRequestProperties(headers);return new ExoPlayer.Builder(this).setMediaSourceFactory(new DefaultMediaSourceFactory(http)).build();}
 private void startSource(int token){if(token!=generation||sources.isEmpty())return;releasePlayer();prepared=false;playing=false;state=retryRound>0||sourceIndex>0?"reconnecting":"connecting";currentUrl=sources.get(sourceIndex);updateMetadata();startForeground(NOTIFICATION_ID,buildNotification());broadcastState();if(PlaylistResolver.shouldResolve(currentUrl)){final String playlist=currentUrl;new Thread(()->{try{String resolved=PlaylistResolver.resolve(playlist);handler.post(()->{if(token!=generation)return;currentUrl=resolved;startResolvedSource(token);});}catch(Exception e){handler.post(()->failSource(token));}}).start();return;}startResolvedSource(token);}
 private void startResolvedSource(int token){if(token!=generation)return;AudioAttributes aa=new AudioAttributes.Builder().setUsage(C.USAGE_MEDIA).setContentType(C.AUDIO_CONTENT_TYPE_MUSIC).build();player=buildPlayer();player.setAudioAttributes(aa,true);player.setWakeMode(C.WAKE_MODE_NETWORK);player.setHandleAudioBecomingNoisy(true);player.addListener(new Player.Listener(){@Override public void onPlaybackStateChanged(int ps){if(token!=generation)return;if(ps==Player.STATE_READY){prepared=true;if(player!=null&&!player.isPlaying())player.play();}else if(ps==Player.STATE_BUFFERING){state=sourceIndex>0||retryRound>0?"reconnecting":"connecting";}else if(ps==Player.STATE_ENDED){failSource(token);}syncPlayerState();}@Override public void onIsPlayingChanged(boolean p){if(token!=generation)return;playing=p;if(p){prepared=true;retryRound=0;state="playing";}else if(prepared&&player!=null&&player.getPlaybackState()==Player.STATE_READY)state="paused";updatePlaybackState();refreshNotification();broadcastState();}@Override public void onPlayerError(PlaybackException error){if(token==generation)failSource(token);}});try{MediaItem item=MediaItem.fromUri(currentUrl);player.setMediaItem(item);player.prepare();player.play();}catch(Exception e){failSource(token);}}
 private void syncPlayerState(){if(player==null)return;int ps=player.getPlaybackState();if(ps==Player.STATE_BUFFERING)state=sourceIndex>0||retryRound>0?"reconnecting":"connecting";else if(ps==Player.STATE_READY&&player.isPlaying()){prepared=true;playing=true;state="playing";}updatePlaybackState();refreshNotification();broadcastState();}
 private void failSource(int token){if(token!=generation)return;prepared=false;playing=false;releasePlayer();sourceIndex++;if(sourceIndex>=sources.size()){sourceIndex=0;retryRound++;}if(retryRound<=2){state="reconnecting";refreshNotification();broadcastState();long delay=Math.min(8000L,1200L*(retryRound+1));retryRunnable=()->startSource(token);handler.postDelayed(retryRunnable,delay);}else{state="error";updatePlaybackState();refreshNotification();broadcastState();}}
 private void cancelRetry(){if(retryRunnable!=null){handler.removeCallbacks(retryRunnable);retryRunnable=null;}}
 private void togglePlayback(){if(player==null){if(!sources.isEmpty()){retryRound=0;startSource(generation);}return;}try{if(player.isPlaying()){player.pause();playing=false;state="paused";}else{player.play();}updatePlaybackState();refreshNotification();broadcastState();}catch(Exception e){failSource(generation);}}
 private List<Station> orderedStations(){List<Station> ordered=new ArrayList<>();String raw=getSharedPreferences(PREFS,MODE_PRIVATE).getString(ORDER,"");if(raw!=null&&!raw.isEmpty()){for(String n:raw.split(SEP,-1)){Station s=Stations.find(n);if(s!=null&&!ordered.contains(s))ordered.add(s);}}for(Station s:Stations.ALL)if(!ordered.contains(s))ordered.add(s);return ordered;}
 private void changeStation(int d){List<Station> order=orderedStations();if(order.isEmpty())return;int c=-1;for(int x=0;x<order.size();x++)if(order.get(x).name.equals(currentName)){c=x;break;}for(int step=1;step<=order.size();step++){int idx=(c+d*step)%order.size();if(idx<0)idx+=order.size();Station s=order.get(idx);if(s.hasStream()){playStation(s.name,s.streamUrl);return;}}}
 private void stopPlayback(boolean remove){generation++;cancelRetry();cancelSleep();releasePlayer();prepared=false;playing=false;state="stopped";updatePlaybackState();broadcastState();if(remove){stopForeground(STOP_FOREGROUND_REMOVE);currentName="";currentUrl="";sources=Collections.emptyList();stationArt=null;stopSelf();}}
 private void releasePlayer(){if(player!=null){try{player.stop();player.clearMediaItems();player.release();}catch(Exception ignored){}player=null;}}
 private void scheduleSleep(int m){cancelSleep();if(m>0){sleepRunnable=()->stopPlayback(true);handler.postDelayed(sleepRunnable,m*60000L);}}
 private void cancelSleep(){if(sleepRunnable!=null){handler.removeCallbacks(sleepRunnable);sleepRunnable=null;}}
 private void createMediaSession(){mediaSession=new MediaSession(this,"RadioMarocSession");mediaSession.setCallback(new MediaSession.Callback(){@Override public void onPlay(){if(!playing)togglePlayback();}@Override public void onPause(){if(playing)togglePlayback();}@Override public void onStop(){stopPlayback(true);}@Override public void onSkipToNext(){changeStation(1);}@Override public void onSkipToPrevious(){changeStation(-1);}});mediaSession.setFlags(MediaSession.FLAG_HANDLES_MEDIA_BUTTONS|MediaSession.FLAG_HANDLES_TRANSPORT_CONTROLS);mediaSession.setActive(true);updatePlaybackState();}
 private void updatePlaybackState(){if(mediaSession==null)return;int ps=playing?PlaybackState.STATE_PLAYING:(prepared?PlaybackState.STATE_PAUSED:(("connecting".equals(state)||"reconnecting".equals(state))?PlaybackState.STATE_BUFFERING:PlaybackState.STATE_STOPPED));long a=PlaybackState.ACTION_PLAY|PlaybackState.ACTION_PAUSE|PlaybackState.ACTION_PLAY_PAUSE|PlaybackState.ACTION_STOP|PlaybackState.ACTION_SKIP_TO_NEXT|PlaybackState.ACTION_SKIP_TO_PREVIOUS;mediaSession.setPlaybackState(new PlaybackState.Builder().setActions(a).setState(ps,PlaybackState.PLAYBACK_POSITION_UNKNOWN,playing?1f:0f).build());}
 private void updateMetadata(){if(mediaSession==null)return;MediaMetadata.Builder b=new MediaMetadata.Builder().putString(MediaMetadata.METADATA_KEY_TITLE,currentName).putString(MediaMetadata.METADATA_KEY_ARTIST,"Radio Maroc");if(stationArt!=null)b.putBitmap(MediaMetadata.METADATA_KEY_ART,stationArt).putBitmap(MediaMetadata.METADATA_KEY_ALBUM_ART,stationArt);mediaSession.setMetadata(b.build());}
 private void loadStationArt(String name){Station s=Stations.find(name);if(s==null||s.logoUrl==null||s.logoUrl.isEmpty())return;new Thread(()->{try(InputStream in=new URL(s.logoUrl).openStream()){Bitmap b=BitmapFactory.decodeStream(in);if(b!=null){stationArt=b;handler.post(()->{updateMetadata();refreshNotification();});}}catch(Exception ignored){}}).start();}
 private PendingIntent servicePI(String a,int r){return PendingIntent.getService(this,r,new Intent(this,RadioService.class).setAction(a),PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);}
 private Notification buildNotification(){PendingIntent open=PendingIntent.getActivity(this,0,new Intent(this,MainActivity.class),PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,CHANNEL_ID):new Notification.Builder(this);int ti=playing?R.drawable.ic_pause:R.drawable.ic_play;b.setSmallIcon(R.drawable.ic_radio).setContentTitle(currentName.isEmpty()?"Radio Maroc":currentName).setContentText(notificationStateText()).setContentIntent(open).setOnlyAlertOnce(true).setVisibility(Notification.VISIBILITY_PUBLIC).setCategory(Notification.CATEGORY_TRANSPORT).setOngoing(playing||"connecting".equals(state)||"reconnecting".equals(state)).setDeleteIntent(servicePI(ACTION_STOP,9));if(stationArt!=null)b.setLargeIcon(stationArt);b.addAction(new Notification.Action.Builder(R.drawable.ic_previous,t("السابق","Précédent","Previous"),servicePI(ACTION_PREVIOUS,3)).build()).addAction(new Notification.Action.Builder(ti,playing?t("توقف مؤقت","Pause","Pause"):t("تشغيل","Lire","Play"),servicePI(ACTION_TOGGLE,1)).build()).addAction(new Notification.Action.Builder(R.drawable.ic_next,t("التالي","Suivant","Next"),servicePI(ACTION_NEXT,4)).build()).addAction(new Notification.Action.Builder(R.drawable.ic_stop,"✕",servicePI(ACTION_STOP,2)).build()).setStyle(new Notification.MediaStyle().setShowActionsInCompactView(0,1,2).setMediaSession(mediaSession.getSessionToken()));return b.build();}
 private void refreshNotification(){if(!currentName.isEmpty())((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(NOTIFICATION_ID,buildNotification());}
 private String notificationStateText(){if("connecting".equals(state))return t("جاري الاتصال…","Connexion…","Connecting…");if("reconnecting".equals(state))return t("تبديل مصدر البث…","Reconnexion…","Switching stream…");if("playing".equals(state))return t("يعمل الآن","Lecture en cours","Playing now");if("paused".equals(state))return t("متوقف مؤقتًا","En pause","Paused");if("error".equals(state))return t("البث غير متاح حاليًا","Flux indisponible","Stream unavailable");return t("متوقف","Arrêté","Stopped");}
 private String t(String ar,String fr,String en){String l=getSharedPreferences(PREFS,MODE_PRIVATE).getString("lang","en");return "ar".equals(l)?ar:("fr".equals(l)?fr:en);}
 private void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel(CHANNEL_ID,"Radio Maroc",NotificationManager.IMPORTANCE_LOW);c.setDescription("Background radio playback controls");c.setShowBadge(false);getSystemService(NotificationManager.class).createNotificationChannel(c);}}
 private void broadcastState(){Intent i=new Intent("com.master.radiomaroc.STATE");i.setPackage(getPackageName());i.putExtra("state",state);i.putExtra("playing",playing);i.putExtra("station",currentName);sendBroadcast(i);}
 @Override public void onDestroy(){generation++;cancelRetry();cancelSleep();releasePlayer();if(mediaSession!=null){mediaSession.setActive(false);mediaSession.release();}super.onDestroy();}
 @Override public IBinder onBind(Intent i){return null;}
}